version: 2.1

executors:
  docker-latest:
    docker:
      - image: docker:git
    resource_class: medium
  cimg:
    docker:
      - image: cimg/base:current
        user: root
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    resource_class: small

commands:
  build:
    parameters:
      build_args:
        default: ''
        type: string
      dockerfile:
        default: Dockerfile
        type: string
      local_image_name:
        default: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:10}
        type: string
      path:
        default: .
        type: string
      workspace:
        default: ''
        type: string
    steps:
      - when:
          condition: <<parameters.workspace>>
          steps:
            - attach_workspace:
                at: <<parameters.workspace>>
            - run: mv <<parameters.workspace>>/* <<parameters.path>>/
      - run:
          name: docker build
          command: |
            docker build \
              <<parameters.build_args>> \
              --progress=plain \
              -f <<parameters.path>>/<<parameters.dockerfile>> \
              -t <<parameters.local_image_name>> \
              <<parameters.path>>
          environment:
            DOCKER_BUILDKIT: 1

  tag:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      local_image_name:
        default: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:10}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - tag-with-commit:
          image: <<parameters.image>>
          local_image_name: <<parameters.local_image_name>>
          registry: <<parameters.registry>>
      - tag-with-branch:
          image: <<parameters.image>>
          local_image_name: <<parameters.local_image_name>>
          registry: <<parameters.registry>>
      - tag-with-tag:
          image: <<parameters.image>>
          local_image_name: <<parameters.local_image_name>>
          registry: <<parameters.registry>>
      - run: # Added condition for tag-with-latest
          name: docker tag (latest)
          command: |
            if [[ "${CIRCLE_BRANCH}" == "main" || "${CIRCLE_BRANCH}" == "master" ]]; then
              docker tag \
                "<<parameters.local_image_name>>" \
                "<<parameters.registry>>/<<parameters.image>>:latest"
            else
              echo "Not tagging with latest"
            fi

  tag-with-commit:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      local_image_name:
        default: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:10}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker tag (commit)
          command: |
            docker tag \
              "<<parameters.local_image_name>>" \
              "<<parameters.registry>>/<<parameters.image>>:${CIRCLE_SHA1:0:10}"

  tag-with-branch:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      local_image_name:
        default: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:10}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker tag (branch)
          command: |
            if [[ -n "${CIRCLE_BRANCH}" ]]; then
              docker tag \
                "<<parameters.local_image_name>>" \
                "<<parameters.registry>>/<<parameters.image>>:${CIRCLE_BRANCH//\//-}"
            fi

  tag-with-latest:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      local_image_name:
        default: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:10}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker tag (latest)
          command: |
            docker tag \
              "<<parameters.local_image_name>>" \
              "<<parameters.registry>>/<<parameters.image>>:latest"

  tag-with-tag:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      local_image_name:
        default: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1:0:10}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker tag (tag)
          command: |
            if [[ -n "${CIRCLE_TAG}" ]]; then
              docker tag \
                "<<parameters.local_image_name>>" \
                "<<parameters.registry>>/<<parameters.image>>:${CIRCLE_TAG}"
            fi

  push:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker push (all-tags)
          command: |
            docker push --all-tags <<parameters.registry>>/<<parameters.image>>

  push-with-commit:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker push (commit)
          command: |
            docker push "<<parameters.registry>>/<<parameters.image>>:${CIRCLE_SHA1:0:10}"

  push-with-branch:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker push (branch)
          command: |
            if [[ -n "${CIRCLE_BRANCH}" ]]; then
              docker push "<<parameters.registry>>/<<parameters.image>>:${CIRCLE_BRANCH//\//-}"
            fi

  push-with-latest:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      registry:
        default: 'docker.io'
        type: string
    steps:
      - run:
          name: docker push (latest)
          command: |
            docker push "<<parameters.registry>>/<<parameters.image>>:latest"

  push-with-tag:
    parameters:
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      registry:
        default: 'docker.io'
        type: string
      tag:
        default: ${CIRCLE_TAG}
        type: string
    steps:
      - run:
          name: docker push (tag)
          command: |
            if [[ -n "<<parameters.tag>>" ]]; then
              docker push "<<parameters.registry>>/<<parameters.image>>:<<parameters.tag>>"
            fi

jobs:
  compose-run:
    executor: <<parameters.executor>>
    parameters:
      build_args:
        default: ''
        type: string
      compose_args:
        default: '-f docker-compose.yaml'
        type: string
      configure_docker:
        default: []
        type: steps
      cwd:
        default: '.'
        type: string
      docker_layer_caching:
        default: false
        type: boolean
      executor:
        default: cimg
        type: executor
      run_args:
        default: ''
        type: string
      version:
        default: default
        type: string
    steps:
      - setup_remote_docker:
          version: <<parameters.version>>
          docker_layer_caching: <<parameters.docker_layer_caching>>
      - steps: <<parameters.configure_docker>>
      - checkout
      - run:
          command: docker compose <<parameters.compose_args>> build <<parameters.build_args>>
          working_directory: <<parameters.cwd>>
      - run:
          command: docker compose <<parameters.compose_args>> run --rm <<parameters.run_args>>
          working_directory: <<parameters.cwd>>
      - run:
          command: docker compose <<parameters.compose_args>> logs -t | sort -k 3
          when: on_fail
          working_directory: <<parameters.cwd>>


  publish:
    executor: <<parameters.executor>>
    parameters:
      build_args:
        default: ''
        type: string
      dockerfile:
        default: Dockerfile
        type: string
      executor:
        default: docker-latest
        type: executor
      image:
        default: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        type: string
      path:
        default: .
        type: string
      registry:
        default: 'docker.io'
        type: string
      workspace:
        default: ''
        type: string
    steps:
      - checkout
      - build:
          build_args: <<parameters.build_args>>
          dockerfile: <<parameters.dockerfile>>
          path: <<parameters.path>>
          workspace: <<parameters.workspace>>
      - tag:
          image: <<parameters.image>>
          registry: <<parameters.registry>>
      - push:
          image: <<parameters.image>>
          registry: <<parameters.registry>>
