version: 2.1

executors:
  python-latest:
    docker:
      - image: python:latest
    resource_class: small

commands:
  install:
    parameters:
      allow_preview:
        default: false
        type: boolean
      version:
        default: latest
        type: string
    steps:
      - run:
          name: install curl
          command: |
            if which apk >/dev/null; then
              apk add --no-cache --no-progress curl
            elif which apt-get >/dev/null; then
              apt-get update -qy
              apt-get install -qy curl
            else
              echo >&2 "ERROR: could not find supported package manager"
              exit 1
            fi
      - unless:
          condition:
            equal: [ <<parameters.version>>, "latest" ]
          steps:
            - run: echo "export POETRY_VERSION=<<parameters.version>>" >> ${BASH_ENV}
      - when:
          condition: <<parameters.allow_preview>>
          steps:
            - run: echo "export POETRY_PREVIEW=1" >> ${BASH_ENV}
      - run: curl -sSL https://install.python-poetry.org | python3
      - run: echo 'export PATH="/root/.local/bin:${PATH}"' >> ${BASH_ENV}

jobs:
  run:
    executor: <<parameters.executor>>
    parameters:
      commands:
        default: []
        type: steps
      configure_poetry:
        default: []
        type: steps
      cwd:
        default: '.'
        type: string
      executor:
        default: python-latest
        type: executor
      install_flags:
        default: ''
        type: string
      version:
        default: latest
        type: string
    steps:
      - install:
          version: <<parameters.version>>
      - steps: <<parameters.configure_poetry>>
      - checkout
      - run:
          command: poetry install -n --no-ansi <<parameters.install_flags>>
          working_directory: <<parameters.cwd>>
      - steps: <<parameters.commands>>

  publish:
    executor: <<parameters.executor>>
    parameters:
      build:
        default: true
        type: boolean
      build_timeout:
        default: 10m
        type: string
      cwd:
        default: '.'
        type: string
      executor:
        default: python-latest
        type: executor
      password:
        type: string
      repository:
        default: pypi
        type: string
      repository_url:
        default: ''
        type: string
      username:
        type: string
    steps:
      - install
      - checkout
      - run:
          name: validate tag matches pyproject.toml
          command:
            if [[ "${CIRCLE_TAG}" != *"$(poetry version | cut -d ' ' -f2)"* ]]; then
                echo "Version $(poetry version) does not match tag ${CIRCLE_TAG}";
                exit 1;
            fi
          working_directory: <<parameters.cwd>>
      - when:
          condition: <<parameters.build>>
          steps:
            - run:
                command: poetry build
                no_output_timeout: <<parameters.build_timeout>>
                working_directory: <<parameters.cwd>>
      - when:
          condition: << parameters.repository_url >>
          steps:
            - run: poetry config repositories.<<parameters.repository>> <<parameters.repository_url>>
      - run:
          name: poetry publish
          command: poetry publish -r <<parameters.repository>> -u <<parameters.username>> -p <<parameters.password>>
          working_directory: <<parameters.cwd>>
