version: 2.1

executors:
  prek-latest:
    docker:
      - image: ghcr.io/j178/prek:latest
    resource_class: small

jobs:
  run:
    executor: <<parameters.executor>>
    parameters:
      args:
        default: '-a --show-diff-on-failure'
        type: string
      cache_prefix:
        default: ''
        type: string
      config_file:
        default: '.pre-commit-config.yaml'
        type: string
      executor:
        default: prek-latest
        type: executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-prek-<<parameters.cache_prefix>>-{{ checksum "<<parameters.config_file>>" }}
      - run: prek install-hooks -c <<parameters.config_file>>
      - save_cache:
          key: cache-prek-<<parameters.cache_prefix>>-{{ checksum "<<parameters.config_file>>" }}
          paths:
            - ~/.cache/prek
      - run: prek run <<parameters.args>> -c <<parameters.config_file>>
