version: 2.1
description: "Tools for running gcloud commands."

commands:
  auth:
    description: >
      Authenticate the Google Cloud SDK with GCP.
    parameters:
      creds:
        default: GCLOUD_SERVICE_KEY
        description: >
          Name of environment variable storing the base64-encoded service key
          for the GCP project.
        type: env_var_name
      project:
        description: The Google project ID to connect with via the gcloud CLI.
        type: string
      zone:
        default: ""
        type: string
    steps:
      - run: echo "${<<parameters.creds>>}" | base64 -d > /key.json
      - run: gcloud auth activate-service-account --key-file=/key.json
      - run: gcloud --quiet config set project "<<parameters.project>>"
      - when:
          condition: <<parameters.zone>>
          steps:
            - run: gcloud --quiet config set zone "<<parameters.zone>>"

  configure-docker:
    description: >
      Configure a local docker client with authentication to GCR. Requires you
      to have already run gcloud/auth.
    steps:
      - setup_remote_docker
      - run: gcloud auth configure-docker --quiet

  configure-gke:
    description: >
      Configure kubectl pointing to a given cluster in a given zone/region.
      Requires you to have already run gcloud/auth.
    parameters:
      cluster:
        type: string
      zone:
        type: string
    steps:
      - run: echo y | gcloud components install kubectl
      - run: gcloud config set container/cluster <<parameters.cluster>>
      - run: gcloud container clusters get-credentials <<parameters.cluster>> --zone=<<parameters.zone>>

  install:
    description: >
      Install the Google Cloud SDK on a supported executor. Currently supported
      package managers: apk, apt-get.
    steps:
      - run:
          name: install dependencies
          command: |
            if which apk >/dev/null; then
              apk add --no-cache --no-progress bash curl curl-dev python
            elif which apt-get >/dev/null; then
              apt-get update -qy
              apt-get install -qy bash curl python
            else
              echo >&2 "ERROR: could not find supported package manager"
              exit 1
            fi
      - run: curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts
      - run: ln -s /root/google-cloud-sdk/bin/gcloud /usr/bin/gcloud
      - run: ln -s /root/google-cloud-sdk/bin/gsutil /usr/bin/gsutil
      - run: ln -s /root/google-cloud-sdk/bin/docker-credential-gcloud /usr/bin/docker-credential-gcloud

jobs:
  docker-publish:
    description: >
      A variation of the docker/publish job, pre-parametrized for GCR builds.
      This job will build, tag, and push a docker image. It will be tagged with
      all relevant metadata, eg. commit hash, branch (if this is a branch
      build), tag (if this is a tag build), and "latest".
    docker:
      - image: <<parameters.executor>>
    parameters:
      build_args:
        default: ''
        description: >
          Extra flags to pass to docker build.
        type: string
      creds:
        default: GCLOUD_SERVICE_KEY
        description: >
          Name of environment variable storing the base64-encoded service key
          for the GCP project.
        type: env_var_name
      dockerfile:
        default: Dockerfile
        description: >
          Name of dockerfile to use.
        type: string
      executor:
        default: docker:18.06.3-ce-git
        description: >
          Name of the docker image to use to execute the job.
        type: string
      image:
        default: ${CIRCLE_PROJECT_REPONAME}
        description: >
          Name of the target image. Note that this will be prepended by the
          project name (eg. <<parameters.project>>), so the full path your
          image will be pushed to will look like:
          <<parameters.registry>>/<<parameters.project>>/<<parameters.image>>.
        type: string
      path:
        default: .
        description: >
          Path to the build context directory containing your Dockerfile.
        type: string
      project:
        description: >
          Name of GCP project to which we will push.
        type: string
      registry:
        default: 'gcr.io'
        description: >
          Container registry to-be-used.
        type: string
      workspace:
        default: ''
        description: >
          If specified, attaches the specified workspace and copies it into the
          Docker context before building.
        type: string
    steps:
      - install
      - auth:
          creds: <<parameters.creds>>
          project: <<parameters.project>>
      - configure-docker
      - checkout
      - docker/build:
          build_args: <<parameters.build_args>>
          dockerfile: <<parameters.dockerfile>>
          path: <<parameters.path>>
          workspace: <<parameters.workspace>>
      - docker/tag:
          image: <<parameters.project>>/<<parameters.image>>
          registry: <<parameters.registry>>
      - docker/push:
          image: <<parameters.project>>/<<parameters.image>>
          registry: <<parameters.registry>>

orbs:
  docker: thekevjames/docker@1
