name: ci

on: [pull_request, push]

jobs:
  lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          # renovate: datasource=github-releases depName=astral-sh/uv
          version: 0.12.13
          # renovate: datasource=docker depName=python
          python-version: 3.14.7
      - uses: j178/prek-action@v3.0.0
        with:
          # renovate: datasource=pypi depName=prek
          prek-version: 0.5.2
          extra-args: --all-files

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          # renovate: datasource=github-releases depName=astral-sh/uv
          version: 0.12.13
      - run: uv run --frozen pytest
        working-directory: docker-atc1441-exporter
